on:
  workflow_dispatch:
  pull_request:

name: Test website rendering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 0.3.71
      - name: Test rendering Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
